### ISSUE TITLE
Not iterating over array

### ISSUE THREAD

**Issue by adean-consensys** [prometheus-community/json_exporter#104]
I'm attempting to iterate over an array of values being pulled from this path:

```
---
metrics:
- name: list_accounts
  path: '{ .result[].balance }'
  help: List of all balances on all accounts
  labels:
    environment: dev
    message: ${ .message }
    address: '{.result[].address}'
    stale: '{.result[].stale}'

```

Example JSON:
```
{
	"message": "OK",
	"result": [{
			"address": "0xa0ebe0f698a73ea76cf66391e2b1399a2baf13cd",
			"balance": "367401245961890814",
			"stale": true
		},
		{
			"address": "0x9e2487cdd0a428de0b8bd2d9c0e423599e427bd8",
			"balance": "122090861696179776",
			"stale": true
		},
		{
			"address": "0x205fa4d4c33cd85442aa3963d9f338da5af5b293",
			"balance": "380593185906600328",
			"stale": true
		}
	]
}
```

Result:
```
# HELP list_accounts List of all balances on all accounts
# TYPE list_accounts untyped
list_accounts{address="0x205fa4d4c33cd85442aa3963d9f338da5af5b293",environment="dev",message="$OK",stale="true"} 3.8059318631058534e+17
```

Expected result
```
# HELP list_accounts List of all balances on all accounts
# TYPE list_accounts untyped
list_accounts{address="0x205fa4d4c33cd85442aa3963d9f338da5af5b293",environment="dev",message="$OK",stale="true"} 3.8059318631058534e+17
list_accounts{address="0x9e2487cdd0a428de0b8bd2d9c0e423599e427bd8",environment="dev",message="$OK",stale="true"} 1.2209086169617977e+17
list_accounts{address="0xa0ebe0f698a73ea76cf66391e2b1399a2baf13cd",environment="dev",message="$OK",stale="true"} 3.6740124596189081e+17
```

As you can see, it is currently only returning a single value, when there are multiple values in this array.  Using the JSONPath-suggested syntax (`.result[*].balance`) returns an error of `"Failed to convert extracted value to float64"` as it returns an array of values.  I need what is under the 'Expected result' to display.

**Comment by adean-consensys** [comment]
Resolved after looking at other comments.  Adjusted metrics settings to

```
---
metrics:
- name: list_accounts
  type: object
  path: '{$.result[*]}'
  help: List of all balances on all accounts
  labels:
    environment: dev
    message: '{ .message }'
    address: '{ .address}'
    stale: '{ .stale}'
  values:
    value: '{.balance}'

```
