### ISSUE TITLE
ServiceMonitor not encoding ampersands required for multiple URL params

### ISSUE THREAD

**Issue by adean-consensys** [prometheus-community/json_exporter#105]
I have an endpoint that requires two params, as stated in this config snippet:

```
- job_name: blockscout_listaccounts
      metrics_path: /probe
      params:
        module: ["account"]
        action: ["listaccounts"]
      static_configs:
        - targets:
          - http://blockscout:4000/api
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: json-exporter.monitoring:7979
```

It works if I encapsulate a curl request with double quotes

Adding a ServiceMonitor so prometheus can scrape the target is being problematic.  It's encoding question marks but not ampersands, so if you need more than one parameter, this won't work:

```
...
spec:
  endpoints:
  - path: /probe?target=http://blockscout:4000/api?module=account%26action=listaccounts
    targetPort: 7979
...
```

Produces this endpoint in Prometheus targets (notice the pre-encoded ampersand is being re-encoded to %2526):
```
http://10.90.3.153:7979/probe%3Ftarget=http://blockscout.palm:4000/api%3Fmodule=account%2526action=listaccounts
```

```
...
spec:
  endpoints:
  - path: /probe?target=http://blockscout:4000/api?module=account&action=listaccounts
    targetPort: 7979
...
```
Produces this endpoint in Prometheus targets (notice the ampersand when it should be %26):
```
http://10.90.3.153:7979/probe%3Ftarget=http://blockscout:4000/api%3Fmodule=account&action=listaccounts
```

Am I completely missing how to do multiple params in a metrics endpoint and/or ServiceMonitor?

**Comment by adean-consensys** [comment]
I think I found some answers regarding the ServiceMonitor, it also uses params (in a different format of course)

```
spec:
  endpoints:
  - params:
      action:
      - listaccounts
      module:
      - account
    path: /probe?target=http://blockscout:4000/api
    targetPort: 7979
```

But I am still getting a 404 not found, which I still feel is an encoding issue

![image](https://user-images.githubusercontent.com/83668448/122961641-94abd400-d352-11eb-83a5-63f9d3170e36.png)

**Comment by adean-consensys** [comment]
I figured it out.  The ServiceMonitor can take nested params (param that takes prams of its own) like so

```
spec:
  endpoints:
  - path: "/probe"
    params:
      target:
        - http://blockscout:4000/api?module=account&action=listaccounts
    targetPort: 7979
```
