### ISSUE TITLE
[FR] Honor prometheus.yaml params

### ISSUE THREAD

**Issue by adean-consensys** [prometheus-community/json_exporter#106]
Feature Request for Prometheus queries to honor scrape_config params to reduce the complexity of Prometheus service monitors.

Example:

```
 job_name: listaccounts
  metrics_path: /list_accounts
  params:
    module: ["account"]
    action: ["listaccounts"]
  static_configs:
    - targets:
      - https://example.org/api
```

A request to `localhost:7979/list_accounts?target=https://example.org/api` would be the same as a query to `localhost:7979/list_accounts?target=https://example.org/api?action=listaccounts&module=account`
