### ISSUE TITLE
Failed to extract value for metric

### ISSUE THREAD

**Issue by ss666** [prometheus-community/json_exporter#111]
the error is:

> level=error ts=2021-07-08T06:31:03.712Z caller=collector.go:83 msg="Failed to extract value for metric" path={.capacity} err="capacity is not found" metric="Desc{fqName: \"queues_capacity\", help: \"information on queues\", constLabels: {}, variableLabels: [type]}"

my yaml config is:
```
metrics:
- name: queues
  path: "{ .scheduler.schedulerInfo.queues.queue }"
  help: information on queues
  type: object
  labels:
       type: '{.type}'
  values:
       capacity: '{.capacity}'

```

and the json is about queues information which actually comes from YARN REST API (part of):

> {
> 	"scheduler": {
> 		"schedulerInfo": {
> 			"type": "capacityScheduler",
> 			"capacity": 100,
> 			"usedCapacity": 1.0526316,
> 			"maxCapacity": 100,
> 			"queueName": "root",
> 			"queues": {
> 				"queue": [
> 					{
> 						"type": "capacitySchedulerLeafQueueInfo",
> 						"capacity": 10,
> 						"usedCapacity": 10.526316,
> 						"maxCapacity": 100,
>
