### ISSUE TITLE
JSON key with space

### ISSUE THREAD

**Issue by saurabhtodankar** [prometheus-community/json_exporter#113]
{
    "List": "1000000013-N-DN2804-N"
    "BrkList": "DN2804",
    "No of connected clients:": "1",
    "No of Socket Connections:": "37",
    "No of Socket Connected prop true:": "5",
    "REMARKS": "OK"
}

I want to get value of  "no of connected clients"
can anyone pls tell me how can i ?
thanks in advance

**Comment by fredr** [comment]
Not the nicest, but this seems to work. Notice that your JSON is missing a `,`, and many of the keys include `:`
```
metrics:
- name: connected_clients
  type: value
  path: "{$['No\\ of\\ connected\\ clients:']}"
```

**Comment by thewangcj** [comment]
i had the same issue，according to #114，i config like below and it works
json:
```json
    {
        "data": {
            "FAN1": [
                {
                    "Device": "FAN",
                    "Fan": "F1",
                    "Speed (RPM)": "9398.00",
                    "Status": "OK"
                },
                {
                    "Device": "FAN",
                    "Fan": "F2",
                    "Speed (RPM)": "8953.00",
                    "Status": "OK"
                }
            ],
        },
        "executed_command": "show fan",
        "status": "OK",
        "status_message": ""
    }
```
config:
```yaml
  metrics:
  - name: speed_rpm
    path: '{ .data.FAN1[0] }'
    type: object
    labels:
      device: '{.Device}' # static label
    values:
      speed: '{.Speed\ (RPM)}'
```
