### ISSUE TITLE
How to use json_exporter with service discovery

### ISSUE THREAD

**Issue by medzin** [prometheus-community/json_exporter#117]
How to use `json_exporter` with service discovery? So, for example I have multiple `json_exporter` instances on GCP and I want to scrape metrics from them:

```
- job_name: json
    scrape_interval: 60s
    gce_sd_configs:
      - zone: europe-west3-a
        project: xxx
        port: 7979
      - zone: europe-west3-b
        project: xxx
        port: 7979
      - zone: europe-west3-c
        project: xxx
        port: 7979
```
