### ISSUE TITLE
filter using regular expressions

### ISSUE THREAD

**Issue by MarcusCalidus** [prometheus-community/json_exporter#139]
Hi,

I'm trying to filter the payload using a regular expression to fetch numeric values only. As I would like to handle the non numeric values differently. Any chance to do this regex or filter somehow in another way?

**snip from config.yml**
```
metrics:
- name: value
  type: object
  help: numeric value from payload
  path: '{[?(@.value =~ /^-?\d+.?\d*$/ )]}'
  labels:
    name: '{.name}'
    businessGroup: '{.businessGroup}'
    environmentType: '{.environmentType}'
    environmentName: '{.environmentName}'
  values:
    value: '{.value}'
```

**Sample payload**
created with: https://github.com/mulesoft-catalyst/metrics-toolkit
third element was filtered
```
[
    {
        "name": "Users Total",
        "value": 16,
        "businessGroup": "TEST",
        "date": "2022-02-02T08:34:50.897Z",
        "group": "Access Management",
        "environmentType": "NA",
        "environmentName": "NA"
    },
    {
        "name": "Active Users",
        "value": 16,
        "businessGroup": "TEST",
        "date": "2022-02-02T08:34:50.897Z",
        "group": "Access Management",
        "environmentType": "NA",
        "environmentName": "NA"
    },
    {
        "name": "CloudHub Runtime Versions Used",
        "value": "4.4.0",
        "businessGroup": "TEST",
        "date": "2022-02-02T08:34:50.897Z",
        "group": "Runtime Manager - CloudHub",
        "environmentType": "Production",
        "environmentName": "PROD"
    }
]
```

**Error Message:**
```
ts=2022-02-02T09:11:22.206Z caller=collector.go:69 level=error msg="Failed to extract json objects for metric" err="unrecognized character in action: U+007E '~'" metric="Desc{fqName: \"value_value\", help: \"Example of sub-level value scrapes from a json\", constLabels: {}, variableLabels: [name businessGroup environmentType environmentName]}"
```
