### ISSUE TITLE
Support url matching metrics

### ISSUE THREAD

**Issue by yeya24** [prometheus-community/json_exporter#144]
Right now, the json exporter's configuration applies to all the targets. It would be great to define multiple targets metrics in the same file but separate them using some matcher. For example,

``` yaml

   
---
metrics:
- target: http://a.com 
  name: example_global_value
  path: "{ .counter }"
  help: Example of a top-level global value scrape in the json
  labels:
    environment: beta # static label
    location: "planet-{.location}"          # dynamic label

- target: http://b.com 
  name: example_global_value
  path: "{ .counter }"
  help: Example of a top-level global value scrape in the json
  labels:
    environment: beta # static label
    location: "planet-{.location}"          # dynamic label
```

When scraping, only metrics with the matched target will be collected.
