### ISSUE TITLE
deep path's don't work

### ISSUE THREAD

**Issue by chadgrant** [prometheus-community/json_exporter#15]
`$.key.object `

or any variation

`$.key.object+`

does not work on simple json :

`{"key": {"object:"value"} }`

**Comment by artusiep** [comment]
For such a JSON you should specify root path: `path` and name type as an object. (at this moment there are 2 scrape types `value` or `object`)
jsonexporter.yml
```yml
- name: key 
  path: $.key.*   
  type: object
  values:
    object: $.object
```

**Comment by vilva42** [comment]
Noob question. Is there a way to extract substring from a key?
```
{
    "status/5xx": 1234
}
```

```
- name: finagle_http_status
  path: $.status/(.*)
  labels:
    status: $1
```
doesn't extract the status value
