### ISSUE TITLE
Question about setting

### ISSUE THREAD

**Issue by f33r0** [prometheus-community/json_exporter#198]
Good day!
I can't figure out if this exporter needs examples (like grok)? Is it possible to take json directly from the endpoint? Does the endpoint have to contain a .json link?
And how to parse a very simple json, I get only error message: config=`"{\"Headers\":{\"X-Dummy\":\"my-test-header\"},\"Metrics\":null,\"HTTPClientConfig\":{\"proxy_url\":null,\"tls_config\":{\"insecure_skip_verify\":false},\"follow_redirects\":false},\"Body\":{\"Content\":\"\",\"Templatize\":false}}`
In fact, all objects are in the top level, but the parser still does not see them.
`prometheus.yml` is also configured, exporter and endpoint work.
Thank you for help

JSON:
**value may change**
`{"processingBlock":1"targetBlock":1,"totalEntities":1}`

my config.yml:
```
headers:
  X-Dummy: my-test-header

modules:
  metrics:
    - name: name
      type: object
      path: '{.}'
      labels:
        processingBlock: '{.processingBlock}'
        targetBlock: '{.targetBlock}'
        totalEntities: '{.totalEntities}'
  values:
    processingBlock: '{.processingBlock}'
    targetBlock: '{.targetBlock}'
    totalEntities: '{.totalEntities}'

```

**Comment by f33r0** [comment]
It's resolved.
I have different question: could I use multiply modules for parse a different logs?

[https://github.com/prometheus-community/json_exporter/blob/f0027c4bcebd1d4aa278477854c590fcf189e1bf/examples/prometheus.yml#L19](url)

**Comment by dguihal** [comment]
@f33r0 could you give some hints on how you managed to solve this ? I'm basically having same issue

Thanks

**Comment by dguihal** [comment]
OK got it

So for reference, you can use

path: '$'

to do a lookup directly on json root

**Comment by dguihal** [comment]
OK got it

path: '{ $ }'

returns the full json object

**Comment by f33r0** [comment]
> path: '{ $ }'

I took the name of the metric that I needed for path.
```
      - name: processingBlock
        help: text
        path: "{.processingBlock}"
        labels:
          processingBlock: '{processingBlock}'
      - name: targetBlock
        help: targetBlock test
        path: "{.targetBlock}"
```
