### ISSUE TITLE
Metrics with scientific notation format

### ISSUE THREAD

**Issue by StonyBrookReus** [prometheus-community/json_exporter#203]
Hi team,

I was running json exporter on this json:
```
{
  "global": {
    "proxy.process.cache_total_hits": "5645788",
    "proxy.process.cache_total_misses": "8931250"
  }
}
```

Here is the config.yml:
```
modules:
  default:
    metrics:
    - name: ats_metrics_global
      type: object
      valuetype: gauge
      help: ATS metrics scrapped from _stats endpoint
      path: '{.global}'
      labels:
        hostname: '{.proxy\.node\.hostname}'
        cache_total_hits: '{.proxy\.process\.cache_total_hits}'
      values:
        cache_total_misses: '{.proxy\.process\.cache_total_misses}'
    headers:
      X-Dummy: my-test-header
```

Got such output:
```
# HELP ats_metrics_global_cache_total_misses ATS metrics scrapped from _stats endpoint
# TYPE ats_metrics_global_cache_total_misses gauge
ats_metrics_global_cache_total_misses{cache_total_hits="5645788",hostname="zoe-prod-ams-xzrnn"} 8.93125e+06
```

Is it possible to change float format from scientific notation to what it is in original json, like from `8.93125e+06` to `8931250` or `8931250.0`?
