### ISSUE TITLE
Metric not found on large responses

### ISSUE THREAD

**Issue by pl4nty** [prometheus-community/json_exporter#206]
I receive the following error when scraping a 1-3MB JSON response, whereas smaller JSON sources work fine:
```
ts=2023-01-21T06:48:55.880Z caller=collector.go:54 level=error msg="Failed to extract value for metric" path="{ .Aggregated_PerSecondStats.Samples }" err="Aggregated_PerSecondStats is not found" metric="Desc{fqName: \"mcc\", help: \"Per-second stats aggregated over a minute\", constLabels: {}, variableLabels: [environment]}"
```

Config and sample:
```yaml
---
modules:
  default:
    metrics:
    - name: mcc
      path: "{ .Aggregated_PerSecondStats.Samples }"
      help: Per-second stats aggregated over a minute
      labels:
        environment: test
```

```json
{
	"Aggregated_PerSecondStats": {
		"Samples": 0
	}
	[snip]
}
```

The JSON loads/parses correctly when loaded from a pod in the same namespace as `json-exporter`, and I tried using values at the start/end of the object with no success.
