### ISSUE TITLE
scraping https endpoint with invalid cert

### ISSUE THREAD

**Issue by g-rd** [prometheus-community/json_exporter#208]
How can I add tls.verify to false?

**Comment by bergvoll** [comment]
Try adding the following under the module (config.yml):
```yml
    http_client_config:
      tls_config:
        insecure_skip_verify: true
```
