### ISSUE TITLE
Code 200 but no response.

### ISSUE THREAD

**Issue by diogocardoso28** [prometheus-community/json_exporter#220]
I get no erros but I also get no output:

Here's the JSON:
```
{
    "@odata.context": "/redfish/v1/$metadata#Thermal.Thermal",
    "@odata.id": "/redfish/v1/Chassis/System.Embedded.1/Thermal",
    "@odata.type": "#Thermal.v1_4_0.Thermal",
    "Description": "Represents the properties for Temperature and Cooling"
}
```
Here's the config.yml:
```
http_client_config:
  tls_config:
    insecure_skip_verify: true
modules:
  teste:
    metrics:
      - name: example_global_value
        path: "{ .Description }"
        help: Example of a top-level global value scrape in the json
        labels:
          environment: beta
```
And here's my query:
![image](https://user-images.githubusercontent.com/65686179/226490068-36093432-cfc9-4616-a07c-f4dfc4b66157.png)

Also nothing shows up on prometheus or on the containers logs.

I'm I missing something?
