### ISSUE TITLE
dash in name, fails only for boolean values when value is 'false'

### ISSUE THREAD

**Issue by albciff** [prometheus-community/json_exporter#246]
I've a json form jenkins metrics plugins, which looks like:

```json
{
	"disk-space": {
		"healthy": true,
		"timestamp": "2023-06-30T12:13:00.778+02:00"
	},
	"plugins": {
		"healthy": true,
		"timestamp": "2023-06-30T12:13:00.778+02:00"
	},
	"temporary-space": {
		"healthy": true,
		"timestamp": "2023-06-30T12:13:00.778+02:00"
	},
	"thread-deadlock": {
		"healthy": true,
    	        "timestamp": "2023-06-30T12:13:00.778+02:00"
	}
}
```

And a simplified configuration:

```yml
modules:
  default:
    metrics:
    - name: diskspace
      path: '{.disk-space.healthy}'
    - name: plugins
      path: '{.plugins.healthy}'
    - name: temporaryspace
      path: '{.temporary-space.healthy}'
    - name: threaddeadlock
      path: '{.thread-deadlock.healthy}'
```

When "healthy" values are true, all works as expected and the json-exporter returns:

```
# HELP diskspace diskspace
# TYPE diskspace untyped
diskspace 1
# HELP plugins plugins
# TYPE plugins untyped
plugins 1
# HELP temporaryspace temporaryspace
# TYPE temporaryspace untyped
temporaryspace 1
# HELP threaddeadlock threaddeadlock
# TYPE threaddeadlock untyped
threaddeadlock 1
```

However if healthy values change to false, the json-exporter returns a 500 internal server error. But this is only for elements with `-` in the name. If .plugins.healthy it's false, then it works, but if disk-space or temporary-space are false it fails with 500. 

I'm not sure if is a problem with my configuration or a bug in the code. In the logs not appears any information. Can someone provide any guidance? 

Thanks!,
