### ISSUE TITLE
JSON Exporter for Databricks Job Metrics

### ISSUE THREAD

**Issue by kkuram** [prometheus-community/json_exporter#261]
Hello
I am scrape job metrics from databricks spark using their api and converting the json response thruu my grafana agent.. what i am noticing is that the run_id: which is long is being converted to like float/Double number. can you help me suggest what is that i am doing wrong or is this a defect in json exporter

config.yml
```
metrics:
    - name: databricks_job_run_metrics
      type: object
      path: '{.runs[*]}'
      help: Databtricks API 
      labels:
        environment: qa # static label
        run_id: '{.creator_user_name}'
        start_time: '{.start_time}'
        end_time: '{.end_time}'
      values:  
        duration: '{.execution_duration}'
    
```

input:
```
"runs": [
        {
            "job_id": 803954388598194,
            "run_id": 420465847726953,
            "creator_user_name": "UID HERE",
            "number_in_job": 420465847726953,
            "original_attempt_run_id": 420465847726953,
            "state": {
                "life_cycle_state": "RUNNING",
                "state_message": "In run",
                "user_cancelled_or_timedout": false
            },
            "overriding_parameters": {
                "notebook_params": {
                    "DUMMY": "VALUE"
                }
            },
            "start_time": 1696909438455,
            "setup_duration": 1000,
            "execution_duration": 10000,
            "cleanup_duration": 0,
            "end_time": 0,
            "trigger": "ONE_TIME",
            "run_name": "MASKED",
            "run_page_url": "MASK",
            "run_type": "JOB_RUN",
            "format": "MULTI_TASK"
        }]
```
OUTPUT: databricks_job_run_metrics_duration{run_id="1.077467212586853e+15"} 10000
expected o/p: databricks_job_run_metrics_duration{run_id="420465847726953"} 10000
