### ISSUE TITLE
JSONPath problem - maybe...

### ISSUE THREAD

**Issue by mikkop71** [prometheus-community/json_exporter#285]
Hello,

Site I am trying to read returns following json data:

```
{
  "hrmWebFrontStatus": {
    "isAnonymousUser": true,
    "hrmWebFrontVersion": "1.6.2311.2797",
    "hrmWebFrontType": "YKS",
    "maxRequestSize": "~ 20 MiB"
  },
  "hrmBackendStatus": {
    "hrmBackendStatusOk": true,
    "hrmBackendHttpOk": true,
    "hrmBackendType": "YKS",
    "hrmBackendVersion": "1.6.2311.2797",
    "hrmBackendVersionOk": true,
    "hrmBackendDatabaseOk": true,
    "hrmBackendDatabaseVersion": 6830,
    "hrmBackendDatabaseNewestScriptVersion": 6830,
    "hrmBackendDatabaseVersionOk": true,
    "maxRequestSize": "> 30 MiB",
    "hrmBackendMalwareScanOk": true
  },
  "authStatus": {
    "authBothOk": false,
    "authHttpOk": false,
    "exception": true
  }
}
```
My json_exporter config is following:

```
modules:
  default:
    headers:
      MyHeader: MyHeaderValue
    metrics:
      - name: webfrontstatus
        type: object
        help: General statistics of the webfrontstatus
        path: '{.hrmWebFrontStatus}'
        values:
          isAnonymousUser: '{.isAnonymousUser}'
          hrmWebFrontVersion: '{.hrmWebFrontVersion}'
      - name: webbackstatus
        type: object
        help: General statistics of the webbackstatus
        path: '{.hrmBackendStatus}'
        values:
          hrmBackendStatusOk: '{.hrmBackendStatusOk}'
          hrmBackendHttpOk: '{.hrmBackendHttpOk}'
          hrmBackendVersion: '{.hrmBackendVersion}'
          hrmBackendVersionOk: '{.hrmBackendVersionOk}'
          hrmBackendDatabaseOk: '{.hrmBackendDatabaseOk}'
          hrmBackendDatabaseVersion: '{.hrmBackendDatabaseVersion}'
          hrmBackendDatabaseVersionOk: '{.hrmBackendDatabaseVersionOk}'

```

When I try to following command: curl http://localhost:7979/probe?target=xxxweb.xxx.xx/home/status?format=json
nothing seems to happen, no error messages just nothing.

Is there something wrong with the config or how I could debug situtation?
