### ISSUE TITLE
wanted to check which all parameters can be used in config.yml file ?

### ISSUE THREAD

**Issue by mjadwani** [prometheus-community/json_exporter#336]
Hi Team ,

I am from mainframe background and trying to add my data from mainframe which is available in json format to prometheus and came across this json_exporter . Wanted to know which all statements are valid for config.yml file ?
Can you perform bearer token authentication from config.yml file ?
Is there any documentation available how to code this config.yml file ?

**Comment by agardnerIT** [comment]
You'll have to interpret the Go code but it's essentially [here](https://github.com/prometheus-community/json_exporter/blob/master/config/config.go).

For example:

```
---
modules:
  default:
    # headers:
    #   X-Dummy: my-test-header
    metrics:
    - name: my_json_metric
      valuetype: gauge
      path: '{ .my_first_metric }' # Uses JSONPath
      help: This is my first metric transformed from JSON by the json_exporter
      # labels:
      #   environment: beta # static label
        # location: 'planet-{.location}'          # dynamic label
```

For [each metric](https://github.com/prometheus-community/json_exporter/blob/36402ebd673e982e1480299da4fce381ea0c3abd/config/config.go#L24), you're allowed:"

- Name = "name"
- Path = "path"
- Labels = see above
- Type = "type"
- ValueType = "value type"
- EpochTimestamp = "epochtimestamp"
- Help = "help"
- Values = "values"
