### ISSUE TITLE
Is templating supported in basic_auth?

### ISSUE THREAD

**Issue by kalmarz** [prometheus-community/json_exporter#370]
I'd like to pass the credentials as environment variables, similarly to blackbox-exporter:

```
    http_client_config:
      basic_auth:
        username: '{{ env "OS_USERNAME" }}'
        password: '{{ env "OS_PASSWORD" }}'
```

But this doesn't seem to be working as I always get a 403. Is it supported and I miss something?
