### ISSUE TITLE
/probe returns status 503 in Docker

### ISSUE THREAD

**Issue by extremelyonline** [prometheus-community/json_exporter#379]
Hello, I have encountered an error where Prometheus cannot connect to the /probe path:

I have a working json_exporter container. This is verified by exposing the 7979 port and getting results from:

```
curl "http://localhost:7979/probe?module=default&target=https://abc.com/data.json"
```

In a compose file, I put both json_exporter and Prometheus in the same network:

```
  ## gather the metrics of json_exporter application itself
  - job_name: json-exporter
    scrape_interval: 30s
    static_configs:
      - targets:
        - json-exporter:7979

    ## gather the metrics from third party json sources, via the json exporter
  - job_name: json
    metrics_path: /probe
    scrape_interval: 30s
    static_configs:
      - targets:
        - https://abc.com/data.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json-exporter:7979
```

In Prometheus, the `http://json-exporter:7979/metrics` path is UP. The `http://json-exporter:7979/probe` path returns the error "server returned HTTP status 503 Service Unavailable".
