### ISSUE TITLE
Extracting substrings from a key 

### ISSUE THREAD

**Issue by vilva42** [prometheus-community/json_exporter#52]
More of a jsonpath question I guess, if I have a json like the following

```
{
    "route/api_1_test/POST/time/4XX.p9999": 1234
}
```
I'm trying to transform it into
`finagle_http_time{status="4xx",route="api_test",method="POST",metric_type="p9999"}`

```
- name: finagle_http_time
  path: $.route/(.+)/(.+)/time/(.+)\.(.+)
  labels:
    status: "$4"
    route: "$1"
    method: "$2"
    metric_type: "$5"
```
How do I extract the status value from the key? Is this possible with the json_exporter?
