### ISSUE TITLE
Reading json sub level values with JSONPath filter expressions

### ISSUE THREAD

**Issue by AndyLudgate** [prometheus-community/json_exporter#64]
I've been trying to use json_exporter to read an API with the following structure (simplified and no properties available for 2nd element)):

```json
[	
    {
        "machineID": "SG_8284215608661916610",
        "online": true,
        "name": "Oxford Store",
        "uptimeMS": 56725789,
        "properties": [{
                "key": "siteNumber",
                "value": "321"
            }, {
                "key": "customer",
                "value": "Greenchurch"
            }
        ]
    }, {
        "machineID": "SG_3997078225428050463",
        "online": true,
        "name": "Liverpool Store",
        "uptimeMS": 56723784,
        "properties": []
    }
]
```

The following config allows me to extract all of the data except for the properties array:
```yaml
---
metrics:
- name: simplehelp
  type: object
  help: Simplehelp machine Id
  path: $[*]
  labels:
    environment: simplehelp             # static label
    machineId: $.machineID              # dynamic label
    name: $.name
    state: $.state
    uptime: $.uptimeMS
    customer: $.properties[?(@.key=="customer")].value
    siteNumber: $.properties[?(@.key=="siteNumber")].value
  values:
    online: $.online
```

Prometheus output (simplified to reduce space, instance removed etc):
```yaml
simplehelp_online{environment="simplehelp",machineId="SG_8284215608661916610",name="Oxford Store",uptime="56725789"} 1
simplehelp_online{environment="simplehelp",machineId="SG_3997078225428050463",name="Liverpool Store",uptime="56723784"} 1
```

I get an error for the 2 property values:
```log
level=error ts=2020-11-10T16:54:21.423Z caller=collector.go:156 msg="Failed to compile path for label" path="$.properties[?(@.key==\"siteNumber\")].value" err="Expected number, key, or *, but got none"
level=error ts=2020-11-10T16:54:21.423Z caller=collector.go:156 msg="Failed to compile path for label" path="$.properties[?(@.key==\"customer\")].value" err="Expected number, key, or *, but got none"
```

if for the customer and siteNumber I do something like:
```yaml
    customer: $.properties[1].value
    siteNumber: $.properties[0].value
```
then it extracts, but I can't guarantee the position in the array of either value.

I have asked the API maintainer if they can modify the output so the values are mapped like the following which I know I can extract:
```json
"properties": {
    "siteNumber": "321",
    "customer": "greenchurch"
}
```
but it sounds like that might take a while to get done (if ever).

According to some online JSONPath emulators, the config I'm using with filters should work. Can you tell me if I'm doing something wrong or do filters not work in your implementation of JSONPath

ALSO,

It would be a good idea to include an example of configuring Prometheus for the probe stuff. It took me ages to track down how to do it.
