### ISSUE TITLE
"Failed to parse value as float" error when the config file from the example is used

### ISSUE THREAD

**Issue by qmonitoring** [prometheus-community/json_exporter#77]
**Steps to reproduce:**

- Start python server

` python3 -m http.server`

data.json file with content from [example](https://github.com/prometheus-community/json_exporter/blob/master/examples/data.json)

- Start docker container 

`docker run -d  --network=host  -v /opt/jsonexporter/config.yml:/config.yml prometheuscommunity/json-exporter --config.file=/config.yml`

config.yml file with content from [example](https://github.com/prometheus-community/json_exporter/blob/master/examples/data.json)

- Add target info to _prometheus.yml_ configuration file

```
  - job_name: json_exporter
    static_configs:
      - targets:
        - <host_ip>:7979 ## Location of the json exporter's real <hostname>:<port>

  ## gather the metrics from third party json sources, via the json exporter
  - job_name: jsonexporter
    metrics_path: /probe
    static_configs:
      - targets:
        - http://<host_ip>:8080/data.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <host_ip>:7979 ## Location of the json exporter's real <hostname>:<port>
```

**Current behavior:**
 _prometheus-community/json_exporter_ is up and running, self scraping is working (http://<host_ip>:7979/metrics), but metrics scraping from the endpoint (_data.json_) file is failed with a error:

```
level=error ts=2021-02-10T11:06:50.866Z caller=collector.go:55 msg="Failed to extract float value for metric" path="{ .counter }" err="failed to parse value as float; value: \"{ .counter }\"; err: strconv.ParseFloat: parsing \"{ .counter }\": invalid syntax" metric="Desc{fqName: \"example_global_value\", help: \"Example of a top-level global value scrape in the json\", constLabels: {environment=\"beta\",location=\"planet-{.location}\"}, variableLabels: []}"
level=error ts=2021-02-10T11:06:50.866Z caller=collector.go:68 msg="Failed to compile path" path="{.values[?(@.state == \"ACTIVE\")]}" err="Expected $ or @ at start of path instead of  U+007B '{'"
```
I have tried to change the content of the data.json file, like the syntax in the config.yml file, but that did not work. Also I have tried to use public endpoints instead of my python test server - the result is not comforting

**Question:** 
Is this a bug or misconfiguration?  
How to use _json-exporter_ in docker container with the configuration from the example?
