### ISSUE TITLE
Using timestamp from api as timestamp in promehteous metric

### ISSUE THREAD

**Issue by mostafashr** [prometheus-community/json_exporter#80]
Is  there a way to use timestamp from the api data as timestamp in output result? in promehteous documentation in instrumentation part  there is :
```
metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]
```
I have this data from my api:
```
{
  "data": {
    "object1": {
      "label": "test1",
      "value": 25551.671688,
      "timestamp": 1613115501
    },
    "object2": {
      "label": "test1"
      "value": 20630.985927,
      "timestamp": 1613115603
    }
}
```
is it possible to get output like this?
```
example_metrics{label="test1"}   20630.985927   1613115603
example_metrics{label="test1"}   25551.671688   1613115501
```

**Comment by SuperQ** [comment]
It's possible, but usually not what you want. Timestamps are meant for TSDB federation. They disable staleness handling and can break monitoring if you're not careful.

**Comment by mostafashr** [comment]
I couldn't find an example config to make it happen. would you please help?
my example config is :
```
---
metrics:
- name: example
  path: "{ .data }"
  help: Example 
  labels:
    label: '{.label}' 
  values:
    metrics: '{.value}'
```
How should I add the timestamp to the config?

**Comment by rustycl0ck** [comment]
I think what @SuperQ was trying to convey was that Prometheus supports the concept of creating metrics with explicit timestamp.

This exporter however, does not currently support providing external timestamps with the scrapes.

**Comment by fatpat** [comment]
See the PR #97 which adds the option to fetch the timestamp from the json:
```yaml
---
metrics:
- name: example
  path: "{ .data }"
  timestamp: "{ .date }"
  help: Example 
  labels:
    label: '{.label}' 
  values:
    metrics: '{.value}'
```
