### ISSUE TITLE
Missing target URL variable, string helpers and one metrics for each array items

### ISSUE THREAD

**Issue by Boulet-** [prometheus-community/json_exporter#83]
Hello, I tried to parse the following JSON with json_exporter

```
{
  "status": "disconnected",
  "topics": [
    {
      "topic": "production",
      "count": 606037,
      "lag": 485172
    },
   {
      "topic": "production",
      "count": 23403,
      "lag": 2
    },
    {
      "topic": "staging",
      "count": 121,
      "lag": 0
    }
  ]
}
```

But I failed to:
- access to the URL path to keep some part. I want to extract the `main` value from `https://example.org/main/topics`
- create 2 metrics for both `production` topic
- create a metric based on the `status` with something like `$.status == "connected"`

Here the most advanced config I got:
```
metrics:
    - name: json_topics
      type: object
      path: "{ .topics[*] }"
      help: Topic info
      labels:
        channel: "{ .topic }"
      values:
        lag: "{ .lag }"
        count: "{ .count }"
```

Thanks in advance
