### ISSUE TITLE
Metrics: path definition fails

### ISSUE THREAD

**Issue by thomaswetzler** [prometheus-community/json_exporter#84]
I try to read out a Home Automation API. It has about 300 devices connected. Direct access of the api brings back something like:
```
[
  {
    "id": 1,
    "name": "zwave",
    "roomID": 0,
    "type": "com.fibaro.zwavePrimaryController",
    "baseType": "",
 ...
      "setSipUserID": 1,
      "setSipUserPassword": 1
    },
    "created": 1609413176,
    "modified": 1609413176,
    "sortOrder": 2
  },
  {
    "id": 3,
    "name": "Wetter",
    "roomID": 7,
...
```
With a defined metric
```
metrics:
- name: temperature_devices
  type: object
  help: Devices of HC2 with temperature mesurement
  path: '{$[0:310]}'
  labels:
    id: '{@.id}'
    type: '{@.type}'
    name: '{@.name}'
  values:
    id: '{@.id}'
```
the exporter brings back all devices:
```
# HELP temperature_devices_id Devices of HC2 with temperature mesurement
# TYPE temperature_devices_id untyped
temperature_devices_id{id="1",name="zwave",type="com.fibaro.zwavePrimaryController"} 1
temperature_devices_id{id="100",name="UG Az - Rollanden",type="com.fibaro.FGRM222"} 100
temperature_devices_id{id="101",name="UG Az - Steuerung",type="com.fibaro.remoteController"} 101
temperature_devices_id{id="102",name="UG Az - Heizung",type="com.fibaro.zwaveDevice"} 102
temperature_devices_id{id="103",name="UG Az - Heizung",type="com.fibaro.setPoint"} 103
temperature_devices_id{id="104",name="UG Az - Termometer",type="com.fibaro.temperatureSensor"```
```

If I change the path to 
`path: '{$[]}'`      the exporter isn't working
`path: '{$[0:300][?(@.id == "107")]}'` the exporter won't do it too.

So the filtering and unlimited requests seems not to work.
I attached the test data.json to the case.

**Comment by Richie1710** [comment]
Based on jsonpath syntax $[] does not match anything. 
I think what you want to iterate over all is $[0:] but this is in your case pretty much same as $

$[?(@.id=='107')] would be right syntax for special ID

you can use a evaluator like https://jsonpath.com/

**Comment by thomaswetzler** [comment]
The case is solved. 
The error messages aren't meaningful. Labels have to fulfill the task of a primary key for the value: It's not allowed to have two or more values with exactrly the same labels. If that isn't given, the exporter will report an error that a value has the wrong type.  

```
---
metrics:
- name: fibaro_temperature
  type: object
  help: Devices of Fibaro HC2 with temperature mesurement
  path: '{$[?(@.type == "com.fibaro.temperatureSensor")]}'
  labels:
    id: '{@.id}'
    name: '{@.name}'
    room: '{@.roomID}'
  values:
    value: '{@.properties.value}'
```

works fine now.
