### ISSUE TITLE
Dynamic Values Using Filter Errors

### ISSUE THREAD

**Issue by crockk** [prometheus-community/json_exporter#98]
Hi,

I'm using this metrics rule to try and assign the value for each returned row as bool 1 or 0 depending on the existence of a flag:
```
---
metrics:
- name: sites
  type: object
  help: Site statuses
  path: '{$[?(@.identification.type == "site")]}'
  labels:
    name: '{.identification.name}'
    suspended: '{.identification.suspended}'
    type: '{.identification.type}'
    status: '{.identification.status}'
    id: '{.id}'
  values:
    returned: '{?(.identification.status == "active")}'
```

However the filter errors out in the console. I'm new to JSONPath but from the [docs](https://kubernetes.io/docs/reference/kubectl/jsonpath/) I can't tell what I'm doing wrong. The problem is with the filter expression: ` returned: '{?(.identification.status == "active")}'`. The error is:
```
level=error ts=2021-05-07T23:25:35.143Z caller=collector.go:83
msg="Failed to extract value for metric"
path="{?(.identification.status == \"active\")}" err="unrecognized character in action: U+003F '?'"
metric="Desc{fqName: \"sites_returned\", help: \"Site statuses\", constLabels: {}, variableLabels: [suspended type status id name]}"
```

It says it is unrecognized but it is documented so I am left confused 😕
